title: Alena Thomas' Awesome Website  
author: Alena Thomas
email: amthomas@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
Alena Thomas is a junior in East Brunswick High School 

# social links
instagram_username: alena.mary.thomas  
github_username: amthomas2312

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
