title: Alena's Awesome Website
author: Alena Thomas
email: amthomas2312@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an online portfolio of Alena Thomas. 

# social links
instagram_username: your-instagram-handle # alena.mary.thomas
snapchat_username: your-snapchat-handle # alenamaryy
vsco_username: your-vsco-handle # alenamarythomas
github_username:  your-github-handle # amthomas2312


show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
