title: Alena Thomas
author: amthomas2312
email: amthomas@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 This is an online portfolio 

# social links
instagram_username: alena.mary.thomas
github_username:  amthomas2312

theme: minima 

show_excerpts: true # set to false to remove excerpts on the homepage
