title: Alena Thomas's Website
author: Alena Thomas
email: amthomas2312@gmail.com 
description: This is Alena Mary Thomas. Currently a junior at East Brunswick High School. 

# social links
instagram_username: alena.mary.thomas
github_username:  amthomas2312

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
