title: Alena's Awesome Website
author: Alena Thomas
email: amthomas@ebnet.org
description: I am Alena Mary Thomas. Currently a junior at East Brunswick High School, New Jersey. 

# social links
instagram_username: alena.mary.thomas
github_username: amthomas2312
snapchat_username: alenamaryy 
vsco_username: alenamarythomas

show_excerpts: true # set to false to remove excerpts on the homepage
