title: Alena's Awesome Website
author: Alena Thomas
email: amthomas2312@gmail.com 
description: Alena Thomas's online portfolio. She is currently a junior at East Brunswick High School. 

# social links
instagram_username: alena.mary.thomas
github_username:  amthomas2312
snapchat_username: alenamaryy
vsco_username: alenamarythomas

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
