title: Alena's Awesome Website
author: Alena Thomas
email: amthomas2312@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Alena Thomas's online portfolio. She is currently a junior at East Brunswick High School. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
