title: Alena Thomas's Awesome Website
author: Alena Thomas
email: amthomas@ebnet.org
description: This is Alena Thomas' online portfolio. Currently a junior at East Brunswick High School! 

# social links
instagram_username: alena.mary.thomas
github_username: amthomas2312
snapchat_username: alenamaryy

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
